/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "users" CASCADE;

DROP TABLE IF EXISTS "semi" CASCADE;

DROP TABLE IF EXISTS "pc" CASCADE;

DROP TABLE IF EXISTS "department" CASCADE;

DROP TABLE IF EXISTS "versionpo" CASCADE;

DROP TABLE IF EXISTS "po" CASCADE;

DROP TABLE IF EXISTS "category" CASCADE;

DROP TABLE IF EXISTS "roles" CASCADE;

CREATE TABLE "roles" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name_role" TEXT NOT NULL);

CREATE TABLE "category" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name_category" TEXT NOT NULL);

CREATE TABLE "po" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name_po" TEXT NOT NULL,
  "category" BIGINT NOT NULL,
  CONSTRAINT "category_fk"
    FOREIGN KEY ("category")
    REFERENCES "category" ("id")
    INITIALLY DEFERRED);

CREATE TABLE "versionpo" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "version" TEXT NOT NULL,
  "date_version" TEXT NOT NULL,
  "po" BIGINT NOT NULL,
  CONSTRAINT "po_fk"
    FOREIGN KEY ("po")
    REFERENCES "po" ("id")
    INITIALLY DEFERRED);

CREATE TABLE "department" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name_department" TEXT NOT NULL);

CREATE TABLE "pc" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name_pc" TEXT NOT NULL,
  "department" BIGINT NOT NULL,
  CONSTRAINT "department_fk"
    FOREIGN KEY ("department")
    REFERENCES "department" ("id")
    INITIALLY DEFERRED);

CREATE TABLE "semi" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "po" BIGINT NOT NULL,
  "pc" BIGINT NOT NULL,
  CONSTRAINT "po_fk"
    FOREIGN KEY ("po")
    REFERENCES "po" ("id")
    INITIALLY DEFERRED,
  CONSTRAINT "pc_fk"
    FOREIGN KEY ("pc")
    REFERENCES "pc" ("id")
    INITIALLY DEFERRED);

CREATE TABLE "users" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name_user" TEXT NOT NULL,
  "department" BIGINT NOT NULL,
  "roles" BIGINT NOT NULL,
  CONSTRAINT "department_fk"
    FOREIGN KEY ("department")
    REFERENCES "department" ("id")
    INITIALLY DEFERRED,
  CONSTRAINT "roles_fk"
    FOREIGN KEY ("roles")
    REFERENCES "roles" ("id")
    INITIALLY DEFERRED);

