// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef ALL_TABLES_SINGLE_ODB_HXX
#define ALL_TABLES_SINGLE_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "all_tables_single.h"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Roles
  //
  template <>
  struct class_traits< ::Roles >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Roles >
  {
    public:
    typedef ::Roles object_type;
    typedef ::Roles* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // Category
  //
  template <>
  struct class_traits< ::Category >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Category >
  {
    public:
    typedef ::Category object_type;
    typedef ::Category* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // PO
  //
  template <>
  struct class_traits< ::PO >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::PO >
  {
    public:
    typedef ::PO object_type;
    typedef ::PO* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // VersionPO
  //
  template <>
  struct class_traits< ::VersionPO >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::VersionPO >
  {
    public:
    typedef ::VersionPO object_type;
    typedef ::VersionPO* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // Department
  //
  template <>
  struct class_traits< ::Department >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Department >
  {
    public:
    typedef ::Department object_type;
    typedef ::Department* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // PC
  //
  template <>
  struct class_traits< ::PC >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::PC >
  {
    public:
    typedef ::PC object_type;
    typedef ::PC* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // Semi
  //
  template <>
  struct class_traits< ::Semi >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Semi >
  {
    public:
    typedef ::Semi object_type;
    typedef ::Semi* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // Users
  //
  template <>
  struct class_traits< ::Users >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Users >
  {
    public:
    typedef ::Users object_type;
    typedef ::Users* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // Roles
  //
  template <typename A>
  struct query_columns< ::Roles, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // name_role
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    name_role_type_;

    static const name_role_type_ name_role;
  };

  template <typename A>
  const typename query_columns< ::Roles, id_pgsql, A >::id_type_
  query_columns< ::Roles, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::Roles, id_pgsql, A >::name_role_type_
  query_columns< ::Roles, id_pgsql, A >::
  name_role (A::table_name, "\"name_role\"", 0);

  template <typename A>
  struct pointer_query_columns< ::Roles, id_pgsql, A >:
    query_columns< ::Roles, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::Roles, id_pgsql >:
    public access::object_traits< ::Roles >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // name_role
      //
      details::buffer name_role_value;
      std::size_t name_role_size;
      bool name_role_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 2UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Roles, id_common >:
    public access::object_traits_impl< ::Roles, id_pgsql >
  {
  };

  // Category
  //
  template <typename A>
  struct query_columns< ::Category, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // name
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    name_type_;

    static const name_type_ name;
  };

  template <typename A>
  const typename query_columns< ::Category, id_pgsql, A >::id_type_
  query_columns< ::Category, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::Category, id_pgsql, A >::name_type_
  query_columns< ::Category, id_pgsql, A >::
  name (A::table_name, "\"name_category\"", 0);

  template <typename A>
  struct pointer_query_columns< ::Category, id_pgsql, A >:
    query_columns< ::Category, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::Category, id_pgsql >:
    public access::object_traits< ::Category >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // name
      //
      details::buffer name_value;
      std::size_t name_size;
      bool name_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 2UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Category, id_common >:
    public access::object_traits_impl< ::Category, id_pgsql >
  {
  };

  // PO
  //
  template <typename A>
  struct pointer_query_columns< ::PO, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // name_po
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    name_po_type_;

    static const name_po_type_ name_po;

    // category
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    category_type_;

    static const category_type_ category;
  };

  template <typename A>
  const typename pointer_query_columns< ::PO, id_pgsql, A >::id_type_
  pointer_query_columns< ::PO, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::PO, id_pgsql, A >::name_po_type_
  pointer_query_columns< ::PO, id_pgsql, A >::
  name_po (A::table_name, "\"name_po\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::PO, id_pgsql, A >::category_type_
  pointer_query_columns< ::PO, id_pgsql, A >::
  category (A::table_name, "\"category\"", 0);

  template <>
  class access::object_traits_impl< ::PO, id_pgsql >:
    public access::object_traits< ::PO >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // name_po
      //
      details::buffer name_po_value;
      std::size_t name_po_size;
      bool name_po_null;

      // category
      //
      long long category_value;
      bool category_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct category_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 3UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::PO, id_common >:
    public access::object_traits_impl< ::PO, id_pgsql >
  {
  };

  // VersionPO
  //
  template <typename A>
  struct pointer_query_columns< ::VersionPO, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // version
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    version_type_;

    static const version_type_ version;

    // date_version
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    date_version_type_;

    static const date_version_type_ date_version;

    // po
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    po_type_;

    static const po_type_ po;
  };

  template <typename A>
  const typename pointer_query_columns< ::VersionPO, id_pgsql, A >::id_type_
  pointer_query_columns< ::VersionPO, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::VersionPO, id_pgsql, A >::version_type_
  pointer_query_columns< ::VersionPO, id_pgsql, A >::
  version (A::table_name, "\"version\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::VersionPO, id_pgsql, A >::date_version_type_
  pointer_query_columns< ::VersionPO, id_pgsql, A >::
  date_version (A::table_name, "\"date_version\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::VersionPO, id_pgsql, A >::po_type_
  pointer_query_columns< ::VersionPO, id_pgsql, A >::
  po (A::table_name, "\"po\"", 0);

  template <>
  class access::object_traits_impl< ::VersionPO, id_pgsql >:
    public access::object_traits< ::VersionPO >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // version
      //
      details::buffer version_value;
      std::size_t version_size;
      bool version_null;

      // date_version
      //
      details::buffer date_version_value;
      std::size_t date_version_size;
      bool date_version_null;

      // po
      //
      long long po_value;
      bool po_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct po_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 4UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::VersionPO, id_common >:
    public access::object_traits_impl< ::VersionPO, id_pgsql >
  {
  };

  // Department
  //
  template <typename A>
  struct query_columns< ::Department, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // name
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    name_type_;

    static const name_type_ name;
  };

  template <typename A>
  const typename query_columns< ::Department, id_pgsql, A >::id_type_
  query_columns< ::Department, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::Department, id_pgsql, A >::name_type_
  query_columns< ::Department, id_pgsql, A >::
  name (A::table_name, "\"name_department\"", 0);

  template <typename A>
  struct pointer_query_columns< ::Department, id_pgsql, A >:
    query_columns< ::Department, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::Department, id_pgsql >:
    public access::object_traits< ::Department >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // name
      //
      details::buffer name_value;
      std::size_t name_size;
      bool name_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 2UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Department, id_common >:
    public access::object_traits_impl< ::Department, id_pgsql >
  {
  };

  // PC
  //
  template <typename A>
  struct pointer_query_columns< ::PC, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // name_pc
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    name_pc_type_;

    static const name_pc_type_ name_pc;

    // department
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    department_type_;

    static const department_type_ department;
  };

  template <typename A>
  const typename pointer_query_columns< ::PC, id_pgsql, A >::id_type_
  pointer_query_columns< ::PC, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::PC, id_pgsql, A >::name_pc_type_
  pointer_query_columns< ::PC, id_pgsql, A >::
  name_pc (A::table_name, "\"name_pc\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::PC, id_pgsql, A >::department_type_
  pointer_query_columns< ::PC, id_pgsql, A >::
  department (A::table_name, "\"department\"", 0);

  template <>
  class access::object_traits_impl< ::PC, id_pgsql >:
    public access::object_traits< ::PC >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // name_pc
      //
      details::buffer name_pc_value;
      std::size_t name_pc_size;
      bool name_pc_null;

      // department
      //
      long long department_value;
      bool department_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct department_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 3UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::PC, id_common >:
    public access::object_traits_impl< ::PC, id_pgsql >
  {
  };

  // Semi
  //
  template <typename A>
  struct pointer_query_columns< ::Semi, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // po
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    po_type_;

    static const po_type_ po;

    // pc
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    pc_type_;

    static const pc_type_ pc;
  };

  template <typename A>
  const typename pointer_query_columns< ::Semi, id_pgsql, A >::id_type_
  pointer_query_columns< ::Semi, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::Semi, id_pgsql, A >::po_type_
  pointer_query_columns< ::Semi, id_pgsql, A >::
  po (A::table_name, "\"po\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::Semi, id_pgsql, A >::pc_type_
  pointer_query_columns< ::Semi, id_pgsql, A >::
  pc (A::table_name, "\"pc\"", 0);

  template <>
  class access::object_traits_impl< ::Semi, id_pgsql >:
    public access::object_traits< ::Semi >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // po
      //
      long long po_value;
      bool po_null;

      // pc
      //
      long long pc_value;
      bool pc_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct po_tag;
    struct pc_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 3UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Semi, id_common >:
    public access::object_traits_impl< ::Semi, id_pgsql >
  {
  };

  // Users
  //
  template <typename A>
  struct pointer_query_columns< ::Users, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // name_user
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    name_user_type_;

    static const name_user_type_ name_user;

    // department
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    department_type_;

    static const department_type_ department;

    // roles
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    roles_type_;

    static const roles_type_ roles;
  };

  template <typename A>
  const typename pointer_query_columns< ::Users, id_pgsql, A >::id_type_
  pointer_query_columns< ::Users, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::Users, id_pgsql, A >::name_user_type_
  pointer_query_columns< ::Users, id_pgsql, A >::
  name_user (A::table_name, "\"name_user\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::Users, id_pgsql, A >::department_type_
  pointer_query_columns< ::Users, id_pgsql, A >::
  department (A::table_name, "\"department\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::Users, id_pgsql, A >::roles_type_
  pointer_query_columns< ::Users, id_pgsql, A >::
  roles (A::table_name, "\"roles\"", 0);

  template <>
  class access::object_traits_impl< ::Users, id_pgsql >:
    public access::object_traits< ::Users >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // name_user
      //
      details::buffer name_user_value;
      std::size_t name_user_size;
      bool name_user_null;

      // department
      //
      long long department_value;
      bool department_null;

      // roles
      //
      long long roles_value;
      bool roles_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct department_tag;
    struct roles_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 4UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Users, id_common >:
    public access::object_traits_impl< ::Users, id_pgsql >
  {
  };

  // Roles
  //
  // Category
  //
  // PO
  //
  template <>
  struct alias_traits<
    ::Category,
    id_pgsql,
    access::object_traits_impl< ::PO, id_pgsql >::category_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::PO, id_pgsql >
  {
    // category
    //
    typedef
    odb::alias_traits<
      ::Category,
      id_pgsql,
      access::object_traits_impl< ::PO, id_pgsql >::category_tag>
    category_alias_;
  };

  template <typename A>
  struct query_columns< ::PO, id_pgsql, A >:
    query_columns_base< ::PO, id_pgsql >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // name_po
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    name_po_type_;

    static const name_po_type_ name_po;

    // category
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    category_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::Category,
        id_pgsql,
        category_alias_ > >
    category_pointer_type_;

    struct category_type_: category_pointer_type_, category_column_type_
    {
      category_type_ (const char* t, const char* c, const char* conv)
        : category_column_type_ (t, c, conv)
      {
      }
    };

    static const category_type_ category;
  };

  template <typename A>
  const typename query_columns< ::PO, id_pgsql, A >::id_type_
  query_columns< ::PO, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::PO, id_pgsql, A >::name_po_type_
  query_columns< ::PO, id_pgsql, A >::
  name_po (A::table_name, "\"name_po\"", 0);

  template <typename A>
  const typename query_columns< ::PO, id_pgsql, A >::category_type_
  query_columns< ::PO, id_pgsql, A >::
  category (A::table_name, "\"category\"", 0);

  // VersionPO
  //
  template <>
  struct alias_traits<
    ::PO,
    id_pgsql,
    access::object_traits_impl< ::VersionPO, id_pgsql >::po_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::VersionPO, id_pgsql >
  {
    // po
    //
    typedef
    odb::alias_traits<
      ::PO,
      id_pgsql,
      access::object_traits_impl< ::VersionPO, id_pgsql >::po_tag>
    po_alias_;
  };

  template <typename A>
  struct query_columns< ::VersionPO, id_pgsql, A >:
    query_columns_base< ::VersionPO, id_pgsql >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // version
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    version_type_;

    static const version_type_ version;

    // date_version
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    date_version_type_;

    static const date_version_type_ date_version;

    // po
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    po_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::PO,
        id_pgsql,
        po_alias_ > >
    po_pointer_type_;

    struct po_type_: po_pointer_type_, po_column_type_
    {
      po_type_ (const char* t, const char* c, const char* conv)
        : po_column_type_ (t, c, conv)
      {
      }
    };

    static const po_type_ po;
  };

  template <typename A>
  const typename query_columns< ::VersionPO, id_pgsql, A >::id_type_
  query_columns< ::VersionPO, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::VersionPO, id_pgsql, A >::version_type_
  query_columns< ::VersionPO, id_pgsql, A >::
  version (A::table_name, "\"version\"", 0);

  template <typename A>
  const typename query_columns< ::VersionPO, id_pgsql, A >::date_version_type_
  query_columns< ::VersionPO, id_pgsql, A >::
  date_version (A::table_name, "\"date_version\"", 0);

  template <typename A>
  const typename query_columns< ::VersionPO, id_pgsql, A >::po_type_
  query_columns< ::VersionPO, id_pgsql, A >::
  po (A::table_name, "\"po\"", 0);

  // Department
  //
  // PC
  //
  template <>
  struct alias_traits<
    ::Department,
    id_pgsql,
    access::object_traits_impl< ::PC, id_pgsql >::department_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::PC, id_pgsql >
  {
    // department
    //
    typedef
    odb::alias_traits<
      ::Department,
      id_pgsql,
      access::object_traits_impl< ::PC, id_pgsql >::department_tag>
    department_alias_;
  };

  template <typename A>
  struct query_columns< ::PC, id_pgsql, A >:
    query_columns_base< ::PC, id_pgsql >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // name_pc
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    name_pc_type_;

    static const name_pc_type_ name_pc;

    // department
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    department_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::Department,
        id_pgsql,
        department_alias_ > >
    department_pointer_type_;

    struct department_type_: department_pointer_type_, department_column_type_
    {
      department_type_ (const char* t, const char* c, const char* conv)
        : department_column_type_ (t, c, conv)
      {
      }
    };

    static const department_type_ department;
  };

  template <typename A>
  const typename query_columns< ::PC, id_pgsql, A >::id_type_
  query_columns< ::PC, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::PC, id_pgsql, A >::name_pc_type_
  query_columns< ::PC, id_pgsql, A >::
  name_pc (A::table_name, "\"name_pc\"", 0);

  template <typename A>
  const typename query_columns< ::PC, id_pgsql, A >::department_type_
  query_columns< ::PC, id_pgsql, A >::
  department (A::table_name, "\"department\"", 0);

  // Semi
  //
  template <>
  struct alias_traits<
    ::PO,
    id_pgsql,
    access::object_traits_impl< ::Semi, id_pgsql >::po_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::PC,
    id_pgsql,
    access::object_traits_impl< ::Semi, id_pgsql >::pc_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::Semi, id_pgsql >
  {
    // po
    //
    typedef
    odb::alias_traits<
      ::PO,
      id_pgsql,
      access::object_traits_impl< ::Semi, id_pgsql >::po_tag>
    po_alias_;

    // pc
    //
    typedef
    odb::alias_traits<
      ::PC,
      id_pgsql,
      access::object_traits_impl< ::Semi, id_pgsql >::pc_tag>
    pc_alias_;
  };

  template <typename A>
  struct query_columns< ::Semi, id_pgsql, A >:
    query_columns_base< ::Semi, id_pgsql >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // po
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    po_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::PO,
        id_pgsql,
        po_alias_ > >
    po_pointer_type_;

    struct po_type_: po_pointer_type_, po_column_type_
    {
      po_type_ (const char* t, const char* c, const char* conv)
        : po_column_type_ (t, c, conv)
      {
      }
    };

    static const po_type_ po;

    // pc
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    pc_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::PC,
        id_pgsql,
        pc_alias_ > >
    pc_pointer_type_;

    struct pc_type_: pc_pointer_type_, pc_column_type_
    {
      pc_type_ (const char* t, const char* c, const char* conv)
        : pc_column_type_ (t, c, conv)
      {
      }
    };

    static const pc_type_ pc;
  };

  template <typename A>
  const typename query_columns< ::Semi, id_pgsql, A >::id_type_
  query_columns< ::Semi, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::Semi, id_pgsql, A >::po_type_
  query_columns< ::Semi, id_pgsql, A >::
  po (A::table_name, "\"po\"", 0);

  template <typename A>
  const typename query_columns< ::Semi, id_pgsql, A >::pc_type_
  query_columns< ::Semi, id_pgsql, A >::
  pc (A::table_name, "\"pc\"", 0);

  // Users
  //
  template <>
  struct alias_traits<
    ::Department,
    id_pgsql,
    access::object_traits_impl< ::Users, id_pgsql >::department_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::Roles,
    id_pgsql,
    access::object_traits_impl< ::Users, id_pgsql >::roles_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::Users, id_pgsql >
  {
    // department
    //
    typedef
    odb::alias_traits<
      ::Department,
      id_pgsql,
      access::object_traits_impl< ::Users, id_pgsql >::department_tag>
    department_alias_;

    // roles
    //
    typedef
    odb::alias_traits<
      ::Roles,
      id_pgsql,
      access::object_traits_impl< ::Users, id_pgsql >::roles_tag>
    roles_alias_;
  };

  template <typename A>
  struct query_columns< ::Users, id_pgsql, A >:
    query_columns_base< ::Users, id_pgsql >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // name_user
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    name_user_type_;

    static const name_user_type_ name_user;

    // department
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    department_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::Department,
        id_pgsql,
        department_alias_ > >
    department_pointer_type_;

    struct department_type_: department_pointer_type_, department_column_type_
    {
      department_type_ (const char* t, const char* c, const char* conv)
        : department_column_type_ (t, c, conv)
      {
      }
    };

    static const department_type_ department;

    // roles
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    roles_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::Roles,
        id_pgsql,
        roles_alias_ > >
    roles_pointer_type_;

    struct roles_type_: roles_pointer_type_, roles_column_type_
    {
      roles_type_ (const char* t, const char* c, const char* conv)
        : roles_column_type_ (t, c, conv)
      {
      }
    };

    static const roles_type_ roles;
  };

  template <typename A>
  const typename query_columns< ::Users, id_pgsql, A >::id_type_
  query_columns< ::Users, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::Users, id_pgsql, A >::name_user_type_
  query_columns< ::Users, id_pgsql, A >::
  name_user (A::table_name, "\"name_user\"", 0);

  template <typename A>
  const typename query_columns< ::Users, id_pgsql, A >::department_type_
  query_columns< ::Users, id_pgsql, A >::
  department (A::table_name, "\"department\"", 0);

  template <typename A>
  const typename query_columns< ::Users, id_pgsql, A >::roles_type_
  query_columns< ::Users, id_pgsql, A >::
  roles (A::table_name, "\"roles\"", 0);
}

#include "all_tables_single-odb.ixx"

#include <odb/post.hxx>

#endif // ALL_TABLES_SINGLE_ODB_HXX
